version: '3.8'

services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: tord
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3309:3306"  # Ensure these variable placeholders match your setup or replace with explicit values

  bot:
    image: vulps23/project-encourage:5.2.95
    restart: always  # Automatically restart the bot if it crashes
    depends_on:
      - db
    environment:
      DATABASE: tord
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: 
      DATABASE_PORT: 3306
    logging:
      options:
        max-size: 10m
    ports:
      - "3002:3002"  # Expose port 3002 for the webhook

  wiki:
    image: requarks/wiki:2
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: 
      DB_NAME: wiki
    volumes:
      - ./data/wiki:/wiki/data
    ports:
      - "3003:3000"  # Expose Wiki.js on port 3000

volumes:
  mysql_data: