name: Build and Deploy

on:
  workflow_call
jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'print password' 
        run: echo $password
        env:
          password: ${{ secrets.DOCKER_PASSWORD }}