name: Deploy to Production

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.PRODUCTION_URL }} >> ~/.ssh/known_hosts
          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run remote command via SSH
        uses: D3rHase/ssh-command-action@latest
        with:
          host: ${{ secrets.PRODUCTION_URL }}
          user: ${{ secrets.PRODUCTION_USER }}
          private_key: ${{ secrets.CONTABO_PRIVATE_KEY }}
          host_fingerprint: ${{ secrets.CONTABO_FINGERPRINT }}
          command: echo 'Hello, World!'